name: Build PK3
description: Builds the PK3
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - name: currentDate
    id: current-date
    shell: bash
    run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> "$GITHUB_OUTPUT"
  - uses: montudor/action-zip@v1
    with:
      args: zip -r "uzHDAddon-${{ github.ref_name }}.pk3" . -i brightmaps/* filter/* graphics/* patches/* sprites/* GAMEINFO LANGUAGE.* LICENSE MAPINFO README.md TEXTCOLO TEXTURES.* *.fon2
