name: Build PK3
description: Builds the PK3
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - uses: montudor/action-zip@v1
    with:
      args: zip -r "uzHDAddon-${{ env.SUFFIX }}.pk3" . -i brightmaps/* filter/* graphics/* patches/* sprites/* CHANGELOG.md GAMEINFO LANGUAGE.* LICENSE MAPINFO README.md TEXTCOLO TEXTURES.* TRNSLATE *.fon2
